apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend
  namespace: cybericebox
  labels:
    app: main-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      name: main-frontend
      namespace: cybericebox
      labels:
        app: main-frontend
    spec:
      containers:
        - name: main-frontend
          image: cybericebox/main-frontend:latest
          env:
            - name: NEXT_PUBLIC_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DOMAIN
            - name: NEXT_PUBLIC_RECAPTCHA_SITE_KEY
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: RECAPTCHA_SITE_KEY
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"