apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend
  namespace: cybericebox
  labels:
    app: main-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      name: main-frontend
      namespace: cybericebox
      labels:
        app: main-frontend
    spec:
      containers:
        - name: event-frontend
          image: cybericebox/main-frontend:latest
          envFrom:
            - configMapRef:
                name: config
              prefix: "NEXT_PUBLIC_" # prefix for env variables
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"