#!/bin/sh
# Content-Security-Policy for the static export, generated at container start (after
# 40-next-public-env.sh has substituted the NEXT_PUBLIC_* values).
#
# Why not a nonce: the export is static, so there is no per-request render to stamp a nonce into.
# Instead every inline <script> that the pages (or the client code) can run is hashed here and
# listed in script-src. Sources of inline scripts:
#   1. the <script> elements in out/*.html (Next bootstrap + RSC payload + theme boot script);
#   2. scripts the client creates at runtime (the Google Analytics boot, via next/script). The build
#      step (scripts/csp-inline.mjs) writes their text, with placeholders, to _csp/*.txt; the
#      substitution step has filled them in by now, so the hash matches what the browser executes.
# nginx limits one config string to 4096 bytes, and a site-wide list of hashes is longer than that, so
# each page gets its own hash list through an nginx map keyed by the request URI (conf.d/csp-map.conf),
# and the header snippet interpolates it. frame-ancestors is only honoured as an HTTP header. nginx.conf includes it in the server block and in every location that sets
# its own add_header (add_header is not inherited once a location defines one).
#
# Operator values come from env: NEXT_PUBLIC_API_HOST (connect-src). Vendor sources are added only
# when the app is configured to use them: Google Analytics (NEXT_PUBLIC_GOOGLE_ANALYTICS_ID) and
# the bot-check provider (NEXT_PUBLIC_CAPTCHA_PROVIDER = turnstile | recaptcha, only with NEXT_PUBLIC_DOS_PROTECTION=on). Google sign-in is a top-level navigation through the
# API, so it needs no source here.
set -e

ROOT=/usr/share/nginx/html
OUT=/etc/nginx/snippets/csp.conf
MAP=/etc/nginx/conf.d/csp-map.conf

host=${NEXT_PUBLIC_API_HOST:-}
# A bare host (optionally with a port). Anything else could break the header or the nginx config.
if ! printf '%s' "$host" | grep -Eq '^[A-Za-z0-9.-]+(:[0-9]+)?$'; then
  echo "[csp] NEXT_PUBLIC_API_HOST must be a bare host (got an empty or invalid value)." >&2
  exit 1
fi

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# base64(sha256(file)) of every file given, one per line.
hash_files() {
  sha256sum "$@" | cut -d' ' -f1 | while read -r hex; do
    printf '%s' "$hex" | xxd -r -p | base64 | tr -d '\n'
    echo
  done
}

# 2. Scripts created at runtime by the client code (text emitted at build time). They can run on
# any page, so their hashes go in the fixed part of the header.
common=""
if [ -d "$ROOT/_csp" ]; then
  for f in "$ROOT"/_csp/*.txt; do
    [ -f "$f" ] || continue
    common="$common 'sha256-$(hash_files "$f")'"
  done
  rm -rf "$ROOT/_csp"
fi

# 1. Inline scripts of each exported page: everything between <script ...> (no src) and </script>.
# One map entry per page, for every URI nginx may see for it (/x, /x.html, /dir/, /dir/index.html).
echo '# Generated by csp.sh at container start. Do not edit.' > "$tmp/map"
echo 'map $uri $csp_page_hashes {' >> "$tmp/map"
echo '    default "";' >> "$tmp/map"
pages=0
find "$ROOT" -type f -name '*.html' | sort > "$tmp/pages"
while read -r file; do
  rel=${file#"$ROOT"/}
  if printf '%s' "$rel" | grep -Evq '^[A-Za-z0-9._/-]+$'; then
    echo "[csp] unsupported page file name: $rel" >&2
    exit 1
  fi
  d="$tmp/p$pages"
  mkdir -p "$d"
  awk -v dir="$d" '
    BEGIN { RS = "</script>" }
    {
      i = index($0, "<script")
      if (i == 0) next
      s = substr($0, i)
      j = index(s, ">")
      if (j == 0) next
      if (substr(s, 1, j) ~ /[ \t\n]src=/) next
      body = substr(s, j + 1)
      if (body == "") next
      n++
      f = dir "/" n ".js"
      printf "%s", body > f
      close(f)
    }' "$file"
  pages=$((pages + 1))
  set -- "$d"/*.js
  [ -f "$1" ] || continue
  value=$(hash_files "$@" | sort -u | sed "s/.*/'sha256-&'/" | tr '\n' ' ')
  base=/${rel%.html}
  case "$rel" in
    index.html) keys="/ /index.html" ;;
    */index.html) keys="/${rel%index.html} /${rel%/index.html} /$rel" ;;
    *) keys="$base /$rel" ;;
  esac
  for key in $keys; do
    printf '    "%s" "%s";\n' "$key" "$value" >> "$tmp/map"
  done
done < "$tmp/pages"
echo '}' >> "$tmp/map"

script_src="'self'$common \$csp_page_hashes"
connect_src="'self' https://$host"
frame_src="'none'"

if [ -n "${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID:-}" ]; then
  script_src="$script_src https://www.googletagmanager.com"
  connect_src="$connect_src https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://www.google.com/ccm/ https://*.doubleclick.net"
fi
# This app has no form: the bot check only runs invisibly for the client token, i.e. when DOS protection is on.
if [ "${NEXT_PUBLIC_DOS_PROTECTION:-off}" = "on" ]; then
  case "${NEXT_PUBLIC_CAPTCHA_PROVIDER:-none}" in
    turnstile)
      script_src="$script_src https://challenges.cloudflare.com"
      connect_src="$connect_src https://challenges.cloudflare.com"
      frame_src="https://challenges.cloudflare.com"
      ;;
    recaptcha)
      script_src="$script_src https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/"
      connect_src="$connect_src https://www.google.com/recaptcha/"
      frame_src="https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/"
      ;;
  esac
fi

# style-src keeps 'unsafe-inline': React inline style attributes and Next's <style> tags cannot be
# hashed. Scripts, the risky part, stay strict. img-src allows https: because pictures (avatars,
# event logos) come from the API/media hosts and Google profile photos.
policy="default-src 'self'; script-src $script_src; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src $connect_src; frame-src $frame_src; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'"

mkdir -p "$(dirname "$OUT")"
cp "$tmp/map" "$MAP"
printf 'add_header Content-Security-Policy "%s" always;\n' "$policy" > "$OUT"
echo "[csp] wrote $MAP and $OUT ($pages pages)."
