// Warm-up flag, passed at BUILD time as NEXT_PUBLIC_WARMUP_FLAG. Only this script reads it — src/ must NEVER
// reference it: then Next has nothing to inline and the entrypoint's NEXT_PUBLIC_* loop never finds its name.
// Runs as npm prebuild / predev / pretypecheck. Writes (both gitignored):
//   src/lib/warmup.generated.ts          → SHA-256 of the flag (what the page checks against)
//   public/.well-known/ice/warmup.txt    → base64 of the flag (end of the hint chain: robots.txt → here)
// NEXT_PUBLIC_WARMUP_FLAG comes from the environment (or .env.local / .env). Missing → dev fallback with a
// warning; missing under --strict, CI or NODE_ENV=production → exit 1.
import { createHash } from "node:crypto"
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"

const ROOT = join(import.meta.dirname, "..")
const FORMAT = /^ICE\{[^}]+\}$/
const DEV_FLAG = "ICE{dev_warmup}"

for (const f of [".env.local", ".env"]) {
  const p = join(ROOT, f)
  if (!process.env.NEXT_PUBLIC_WARMUP_FLAG && existsSync(p)) process.loadEnvFile(p)
}

// Placeholder mode (Docker image): bake a hash placeholder and no hint file; the container entrypoint
// computes both from WARMUP_FLAG at start, so the image carries no flag and one image serves any flag.
const PLACEHOLDER = "__WARMUP_SHA256__"
if (process.env.WARMUP_PLACEHOLDER === "1") {
  const p = join(ROOT, "src/lib/warmup.generated.ts")
  mkdirSync(dirname(p), { recursive: true })
  writeFileSync(p, `// Generated by scripts/warmup.mjs — do not edit, do not commit.\nexport const WARMUP_SHA256 = "${PLACEHOLDER}"\n`)
  rmSync(join(ROOT, "public/.well-known/ice/warmup.txt"), { force: true })
  console.log("[warmup] placeholder mode: hash and hint file are written at container start.")
  process.exit(0)
}

const strict = process.argv.includes("--strict") || !!process.env.CI || process.env.NODE_ENV === "production"
let flag = process.env.NEXT_PUBLIC_WARMUP_FLAG?.trim()
if (!flag) {
  if (strict) {
    console.error("[warmup] NEXT_PUBLIC_WARMUP_FLAG is required (format ICE{…}).")
    process.exit(1)
  }
  flag = DEV_FLAG
  console.warn(`[warmup] NEXT_PUBLIC_WARMUP_FLAG is not set — using the dev flag ${DEV_FLAG}.`)
}
if (!FORMAT.test(flag)) {
  console.error("[warmup] NEXT_PUBLIC_WARMUP_FLAG must match ICE{…} (no closing brace inside).")
  process.exit(1)
}

const write = (rel, content) => {
  const p = join(ROOT, rel)
  mkdirSync(dirname(p), { recursive: true })
  writeFileSync(p, content)
}
const sha = createHash("sha256").update(flag, "utf8").digest("hex")
write("src/lib/warmup.generated.ts", `// Generated by scripts/warmup.mjs — do not edit, do not commit.\nexport const WARMUP_SHA256 = "${sha}"\n`)
write("public/.well-known/ice/warmup.txt", Buffer.from(flag, "utf8").toString("base64") + "\n")
console.log("[warmup] flag hash and hint file written.")
